Update README
THBingen/THProjectX pull request #5
Opened 2017-10-16 19:30 UTC by zvenon

Closes #1 
Closes #2
Closes #3 

Musste erst neuen branch (code of conduct) erstellen um diese hinzuzufügen, dann diesen auf release1 geladen..etwas umständlich.

2017-10-16 19:42 UTC, zvenon commented
@nicolaiparlog 
okay zum mergen?

2017-10-17 20:29 UTC, nipafx requested changes

2017-10-17 20:29 UTC, nicolaiparlog commented on README.md
> +English: The code is written in english. Conversations on github an comments (code) are written in english.
> die Kommentare im Code werden in Deutsch geschrieben

> comments (code) are written in english

What now? :wink:

2017-10-17 20:29 UTC, nicolaiparlog commented
Sonst ist alles ok.

2017-10-17 20:54 UTC, zvenon commented on README.md
> +English: The code is written in english. Conversations on github an comments (code) are written in english.
ah. ja, das war dumm 😆

2017-10-18 01:44 UTC, nicolaiparlog commented on README.md
> +English: The code is written in english. Conversations on github an comments (code) are written in german.
Rechtschreibung: 

> English: The code is written in English. Conversations on GitHub and Comments (code) are written in German.

Wenn das korrigiert ist, könnt ihr mergen.

2017-10-18 07:37 UTC, merged